server:
  port: ${PORT:5000}
# Default to "jdbc:postgresql://example.com:5432/database" so that the application at least starts up when
# JDBC_DATABASE_URL is not set. We use this here to reduce friction when newcomers work with this getting started
# application. Production applications should not have a default like this, especially not ones that have credentials
# in them!
token:
  exp:
    minutos: 60
  signing:
    key: ${TOKEN_KEY}
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
springdoc:
  swagger-ui:
    path: /
cloudinary:
  config:
    api:
      name: ${CLOUDINARY_NAME}
      key: ${CLOUDINARY_KEY}
      secret: ${CLOUDINARY_SECRET}
brevio:
  openapi:
    dev-url: http://localhost:5000/
    prod-url: https://safe-savannah-17945-a17a62bf3161.herokuapp.com/